### ISSUE TITLE
[Question]: What are the differences between WNF and Event Tracing? 

### ISSUE THREAD

**Issue by Biswa96** [ionescu007/wnfun#1]
Apology :bow: for hijacking this issue for just asking this question. I've been digging in Windows Event Tracing and WNF since three week (after knowing about BHUSA18 talk). I've found that there are many similarities between ETW and WNF.

* Both has same provider & consumer architecture
* Both are backed by NT kernel
* Both has some GUID/name to specify a session
* One has to subscribe/enable a session name to get logs
* Both provides information about some processes
* Both can be started/stopped from K-mode and/or U-mode (with some privileges)

So, why does Windows (or NT kernel developers) need another method for logging events? Is there any special in WNF which isn't present in Event Tracing?

**Comment by ionescu007** [comment]
Hi,

WNF is not a 'log-file'. It is simply a pub/sub event notification mechanism, so it does not have much in common with ETW.

There is no inherent information in WNF about processes, and WNF cannot be "stopped/started", clients can consume whenever they want to and publishers too. As for being 'backed by kernel and specifying a name', almost anything in any OS functions that way.

I think it's important to simplify as much as possible for your understanding:

* ETW is a tracing/logging mechanism, designed for high-speed logging of activity.
* WNF is a notification mechanism, designed for one-shot, small data payloads associated with a pub/sub model.
